// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "9d96db2a-df4c-4f2f-ab8a-3b54a2faaf02");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1578833946);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1578834066);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578855527);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1578856378);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1578856258);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1578847183);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578760453);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1578834418);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 203176);
user_pref("browser.cache.disk.capacity", 768000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578760393);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{62f676cf-ac0c-4623-951a-ae899047015e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578857342760");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578859161760");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578855557000");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578859157000");
user_pref("browser.search.region", "IE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200107212822");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578855504);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578760405784");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "403a9868829c4d7e9071a1c766449c83");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 10 Jan 2020 11:47:45 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1578833946);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200107212822");
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3be7ef6c-3457-439d-bbaf-454ff2e5dd98\",\"formautofill@mozilla.org\":\"d5c98792-566d-4141-be86-f5a8548c2797\",\"screenshots@mozilla.org\":\"4e58fe63-0809-4ad9-b600-d2d4fd4e57cb\",\"webcompat-reporter@mozilla.org\":\"b5aba999-8935-4ae4-a1e5-4f196bfe8a45\",\"webcompat@mozilla.org\":\"753a8c3e-e1d6-4cea-b317-47b175a8b6e7\",\"default-theme@mozilla.org\":\"5674ef81-7431-49aa-8d87-2019eaf7657d\",\"google@search.mozilla.org\":\"123682a9-55d4-4eb5-88e7-1d77fb2ea9cf\",\"amazondotcom@search.mozilla.org\":\"202a875c-f96c-46b7-b323-3dde518b9db5\",\"bing@search.mozilla.org\":\"94187b85-f5cd-431e-9571-36ffaab23f93\",\"ddg@search.mozilla.org\":\"310cfd46-16f3-4626-a303-094628d13937\",\"ebay@search.mozilla.org\":\"232a7b42-d5d0-408a-afba-92913f0f38b1\",\"twitter@search.mozilla.org\":\"f888cca2-de0e-4f42-9947-0bd76fbb747d\",\"wikipedia@search.mozilla.org\":\"8f00d845-e8e0-4f5b-bb9d-bd481c967d02\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1578838776);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578760421);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200107212822");
user_pref("media.gmp-manager.lastCheck", 1578855615);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1578838777);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "1831e6b8-8cba-464c-adb6-c801613f7235");
user_pref("security.sandbox.plugin.tempDirSuffix", "c74ce2c7-b227-45ec-b664-34218e6a99e0");
user_pref("services.blocklist.pinning.checked", 1578847184);
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_etag", "\"1578787275189\"");
user_pref("services.settings.last_update_seconds", 1578847184);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1578847184);
user_pref("services.settings.main.cfr-fxa.last_check", 1578847184);
user_pref("services.settings.main.cfr.last_check", 1578847184);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578847184);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578847184);
user_pref("services.settings.main.language-dictionaries.last_check", 1578847184);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1578847184);
user_pref("services.settings.main.public-suffix-list.last_check", 1578847184);
user_pref("services.settings.main.sites-classification.last_check", 1578847184);
user_pref("services.settings.main.tippytop.last_check", 1578847184);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578847184);
user_pref("services.settings.main.whats-new-panel.last_check", 1578847184);
user_pref("services.settings.security.onecrl.checked", 1578847184);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1578838777);
user_pref("toolkit.startup.last_success", 1578855488);
user_pref("toolkit.telemetry.cachedClientID", "eb31eb75-7365-437d-8124-914ff9c42536");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
